name: easyflutter
description: A new Flutter project with homeworks.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  retrofit: 2.0.1
  json_annotation: 4.1.0
  mobx: ^2.0.0
  flutter_mobx: ^2.0.2
  http: 0.13.3
  dio: ^4.0.0
  flutter_modular: ^4.3.0
  image_picker: ^0.8.4+4
  path: ^1.8.0
  flutter_speed_dial: ^5.0.0+1
  sqflite: ^2.0.1
  uuid: ^3.0.5
  carousel_slider: ^4.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.0
  build_runner: 2.1.2
  retrofit_generator: 2.0.1+1
  json_serializable: 5.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
